version: '3.1'

services:
  gitlab:
    image: gitlab/gitlab-ce
    command: ""
    restart: always
    hostname:
    ports:
      - 0.0.0.0:1443:443
      - 0.0.0.0:28080:80
    volumes:
      - /app/gitlab/etc:/etc/gitlab
      - /app/gitlab/log:/var/log/gitlab
      - /app/gitlab/data:/var/opt/gitlab
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 512m
networks:
  default:
    external:
      name: env-dev