version: '3.5'

services:
  nexus3:
    image: sonatype/nexus3:3.15.0
    command: ""
    restart: always
    container_name: nexus
    ports:
      - 0.0.0.0:18080:8081
    environment:
      - INSTALL4J_ADD_VM_PARAMS='-Xms600m -Xmx600m -XX:MaxDirectMemorySize=600m -Djava.util.prefs.userRoot=/app/nexus/data/'
      - NEXUS_CONTEXT="nexus"
#    volumes:
      - /app/nexus/data:/nexus-data
    deploy:
      resources:
        limits:
          #          cpus: "0.3"
          memory: 600m

networks:
  default:
    external:
      name: env-dev