version: '3.1'

services:
  db:
    image: mysql:5.7.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: testuser123
    ports:
      - 0.0.0.0:3306:3306
    volumes:
      - /app/mysql/data:/var/lib/mysql
      - /app/mysql/conf.d:/etc/mysql/conf.d
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 512m
networks:
  default:
    external:
      name: env-dev